### ISSUE TITLE
feat: Configuration management system

### ISSUE THREAD

**Issue by takuyakubo** [takuyakubo/llm-as-a-judge#12]
## Overview
現在、設定は環境変数とCLIパラメータのみで管理されており、より柔軟で使いやすい設定管理システムが必要です。

## Current Limitations
- API keyは環境変数のみ（不便、セキュリティリスク）
- プロジェクト固有の設定を保存できない
- デフォルト設定の管理が困難
- チーム間での設定共有ができない
- 設定の階層化や継承ができない

### Configuration File Support
- [ ] YAML設定ファイル（`.llm-judge.yml`, `.llm-judge.yaml`）
- [ ] JSON設定ファイル（`.llm-judge.json`）
- [ ] プロジェクト固有設定（プロジェクトルート）
- [ ] ユーザーグローバル設定（`~/.llm-judge/config.yml`）
- [ ] システム全体設定（`/etc/llm-judge/config.yml`）

### Configuration Hierarchy
優先順位（高→低）:
1. CLI arguments
2. Environment variables  
3. Project config file (`.llm-judge.yml`)
4. User global config (`~/.llm-judge/config.yml`)
5. System config (`/etc/llm-judge/config.yml`)
6. Default values

### Security Features
- [ ] API keyの安全な保存（暗号化オプション）
- [ ] 設定ファイルの権限チェック
- [ ] 機密情報の分離管理
- [ ] `.gitignore`への自動追加提案

### Configuration Options
```yaml
# .llm-judge.yml example
providers:
  openai:
    model: "gpt-4"
    max_tokens: 2000
    temperature: 0.1
    api_key_env: "OPENAI_API_KEY"  # or encrypted value
  anthropic:
    model: "claude-3-5-sonnet-20241022"
    max_tokens: 4000
    temperature: 0.0
    api_key_env: "ANTHROPIC_API_KEY"

defaults:
  provider: "openai"
  output_format: "json"
  verbose: false

evaluation:
  parallel_requests: 3
  retry_attempts: 3
  timeout_seconds: 30

paths:
  rubric_dir: "./rubrics"
  output_dir: "./outputs"
  temp_dir: "/tmp/llm-judge"
```

### Phase 1: Basic Configuration
1. 設定データモデルの定義（Pydantic）
2. YAML/JSON設定ファイルの読み込み
3. 環境変数との統合
4. CLIとの優先順位管理

### Phase 2: Advanced Features
1. 設定ファイルの検索ロジック
2. 設定の継承と上書き
3. 設定の検証とエラーハンドリング
4. 設定のマージ機能

### Phase 3: Security and UX
1. API keyの安全な管理
2. 設定ファイルの生成ウィザード
3. 設定の妥当性チェック
4. ドキュメントとサンプル

## Configuration Schema
```python
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any

class ProviderConfig(BaseModel):
    model: str
    max_tokens: int = 2000
    temperature: float = 0.1
    api_key_env: Optional[str] = None
    api_key: Optional[str] = None  # For encrypted storage

class EvaluationConfig(BaseModel):
    parallel_requests: int = 1
    retry_attempts: int = 3
    timeout_seconds: int = 30
    
class LLMJudgeConfig(BaseModel):
    providers: Dict[str, ProviderConfig] = {}
    defaults: Dict[str, Any] = {}
    evaluation: EvaluationConfig = EvaluationConfig()
    paths: Dict[str, str] = {}
```

## CLI Integration
```bash
# Use specific config file
llm-judge --config custom-config.yml evaluate rubric.json -f doc.txt

# Generate default config
llm-judge config init

# Show current configuration
llm-judge config show

# Set configuration values
llm-judge config set providers.openai.model gpt-4-turbo
llm-judge config set defaults.provider anthropic

# Validate configuration
llm-judge config validate
```

## Security Considerations
- 設定ファイルの権限を600に制限
- API keyの暗号化オプション
- 機密情報の環境変数での上書き推奨
- `.gitignore`への設定ファイル追加警告

## File Structure
```
project/
├── .llm-judge.yml          # Project-specific config
├── .gitignore             
└── evaluations/

~/.llm-judge/
├── config.yml             # User global config
└── api-keys.encrypted     # Encrypted API keys (optional)

/etc/llm-judge/
└── config.yml             # System config (optional)
```

## Dependencies
```python
pyyaml>=6.0         # YAML support
cryptography>=3.0   # API key encryption (optional)
click>=8.0          # Enhanced CLI config commands
```

## Success Criteria
- [ ] YAML設定ファイルでプロジェクト設定を管理できる
- [ ] 設定の階層化と継承が正しく動作する
- [ ] API keyが安全に管理される
- [ ] CLI、環境変数、設定ファイルの優先順位が正しい
- [ ] 設定エラーが分かりやすく表示される
- [ ] チーム間で設定を共有できる

## Priority  
**Medium** - 使いやすさとセキュリティの向上に重要

## Related Issues
- #4 (LLM API integration) - プロバイダー設定の管理
- #11 (Error handling) - 設定エラーの処理
- #5 (Batch evaluation) - バッチ処理の設定管理
