### ISSUE TITLE
feat: Logging and monitoring system

### ISSUE THREAD

**Issue by takuyakubo** [takuyakubo/llm-as-a-judge#13]
## Overview
現在のシステムには構造化されたログ機能と監視機能が不足しており、プロダクション環境での運用とデバッグに必要な可視性が不足しています。

## Current State
- 基本的なprintステートメントのみ
- エラー発生時のデバッグ情報が不足
- API使用量の追跡ができない
- パフォーマンス分析ができない
- 運用監視データがない

### Structured Logging
- [ ] 構造化ログ（JSON形式）
- [ ] ログレベル管理（DEBUG, INFO, WARN, ERROR）
- [ ] コンテキスト情報の自動付与
- [ ] ログローテーション機能
- [ ] 機密情報の自動マスキング

### Application Monitoring
- [ ] API レスポンス時間の測定
- [ ] API使用量とコストの追跡
- [ ] エラー率の監視
- [ ] メモリ使用量の監視
- [ ] 評価処理の進捗追跡

### Performance Analytics
- [ ] 評価処理時間の分析
- [ ] LLMプロバイダー間のパフォーマンス比較
- [ ] ボトルネック検出
- [ ] 使用パターンの分析

### Debug and Troubleshooting
- [ ] 詳細デバッグモード
- [ ] リクエスト/レスポンスのトレース
- [ ] エラー発生時のコンテキスト保存
- [ ] 設定とシステム情報のダンプ

### Phase 1: Core Logging Infrastructure
```python
import structlog
import logging
from datetime import datetime
from typing import Any, Dict

# Structured logger setup
logger = structlog.get_logger()

class LLMJudgeLogger:
    def __init__(self, component: str):
        self.logger = structlog.get_logger(component=component)
    
    def log_evaluation_start(self, rubric: str, document: str, provider: str):
        self.logger.info(
            "evaluation_started",
            rubric=rubric,
            document_length=len(document),
            provider=provider,
            timestamp=datetime.utcnow().isoformat()
        )
    
    def log_api_call(self, provider: str, model: str, tokens: int, response_time: float):
        self.logger.info(
            "api_call_completed",
            provider=provider,
            model=model,
            tokens_used=tokens,
            response_time_ms=response_time * 1000,
            timestamp=datetime.utcnow().isoformat()
        )
```

### Phase 2: Metrics Collection
```python
from dataclasses import dataclass
from typing import Counter
import time

@dataclass
class EvaluationMetrics:
    start_time: float
    end_time: float
    provider: str
    model: str
    tokens_used: int
    cost_estimate: float
    success: bool
    error_type: Optional[str] = None

class MetricsCollector:
    def __init__(self):
        self.metrics: List[EvaluationMetrics] = []
        
    def record_evaluation(self, metrics: EvaluationMetrics):
        self.metrics.append(metrics)
        
    def get_summary(self) -> Dict[str, Any]:
        return {
            "total_evaluations": len(self.metrics),
            "success_rate": self.calculate_success_rate(),
            "average_response_time": self.calculate_avg_response_time(),
            "total_cost": self.calculate_total_cost(),
            "provider_usage": self.get_provider_usage()
        }
```

### Phase 3: Monitoring Dashboard
- リアルタイム使用量表示
- エラー傾向の分析
- コスト分析とアラート
- パフォーマンス傾向

## Logging Configuration
```yaml
# logging.yml
version: 1
formatters:
  json:
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
    
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/llm-judge.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: logs/llm-judge-errors.log
    maxBytes: 10485760
    backupCount: 10

loggers:
  llm_judge:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false

root:
  level: WARNING
  handlers: [console]
```

## CLI Integration
```bash
# Enable debug logging
llm-judge evaluate rubric.json -f doc.txt --log-level debug

# Output logs to specific file
llm-judge evaluate rubric.json -f doc.txt --log-file evaluation.log

# Monitor mode (real-time metrics)
llm-judge monitor --tail-logs

# Generate usage report
llm-judge report --start-date 2024-01-01 --end-date 2024-01-31

# Export metrics
llm-judge metrics export --format json --output metrics.json
```

### Real-time Monitoring
- API call frequency and success rate
- Response time trends  
- Error occurrence patterns
- Cost accumulation

### Alerting System
- Error rate thresholds
- Cost limit warnings
- Performance degradation alerts
- Unusual usage patterns

### Reports and Analytics
```python
# Usage report example
{
  "period": "2024-01-01 to 2024-01-31",
  "total_evaluations": 1250,
  "success_rate": 0.987,
  "providers": {
    "openai": {
      "calls": 800,
      "tokens": 1200000,
      "cost": 24.50,
      "avg_response_time": 2.3
    },
    "anthropic": {
      "calls": 450,
      "tokens": 900000,
      "cost": 15.75,
      "avg_response_time": 1.8
    }
  },
  "errors": {
    "rate_limit": 8,
    "timeout": 3,
    "api_error": 5
  }
}
```

## Security and Privacy
- API keyとuser dataの自動マスキング
- ログファイルの適切な権限設定
- 機密情報のローテーション
- GDPR準拠のデータ保持ポリシー

## Dependencies
```python
structlog>=23.0.0         # Structured logging
python-json-logger>=2.0.0 # JSON formatter
prometheus-client>=0.15.0 # Metrics collection (optional)
```

## File Structure
```
logs/
├── llm-judge.log          # Application logs
├── llm-judge-errors.log   # Error logs
└── metrics.jsonl          # Metrics data

config/
└── logging.yml            # Logging configuration
```

## Success Criteria
- [ ] 全てのAPI呼び出しがログに記録される
- [ ] エラー発生時に十分なデバッグ情報が得られる
- [ ] API使用量とコストが正確に追跡される
- [ ] パフォーマンス問題を特定できる
- [ ] 運用チームが必要な情報を得られる
- [ ] ログの機密情報が適切に保護される

## Priority
**Medium** - 運用とデバッグの改善に重要

## Related Issues
- #11 (Error handling) - エラーログとの統合
- #10 (Integration testing) - テスト実行ログ
- #4 (LLM API integration) - API呼び出しの監視
- #5 (Batch evaluation) - バッチ処理の進捗監視
